-- MySQL Script generated by MySQL Workbench
-- Wed Feb 15 21:09:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema eg_bbs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eg_bbs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eg_bbs` DEFAULT CHARACTER SET utf8 ;
USE `eg_bbs` ;

-- -----------------------------------------------------
-- Table `eg_bbs`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eg_bbs`.`users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `login_id` VARCHAR(32) NOT NULL COMMENT 'ログインID（※ユニーク成約。同一のログインIDは存在しない。）',
  `password` VARCHAR(32) NOT NULL COMMENT 'パスワード',
  `name` VARCHAR(32) NOT NULL COMMENT '名前',
  `created` DATETIME NOT NULL COMMENT '作成日時',
  `updated` DATETIME NOT NULL COMMENT '更新日時',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_id_UNIQUE` (`login_id` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'ユーザー';


-- -----------------------------------------------------
-- Table `eg_bbs`.`topics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eg_bbs`.`topics` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `users_id` BIGINT NOT NULL COMMENT 'ユーザーID',
  `title` VARCHAR(128) NOT NULL COMMENT 'タイトル',
  `body` TEXT NOT NULL COMMENT '本文（※アプリで2000文字の制御を入れる。）',
  `created` DATETIME NOT NULL COMMENT '作成日時',
  `updated` DATETIME NOT NULL COMMENT '更新日時',
  PRIMARY KEY (`id`),
  INDEX `fk_topics_users1_idx` (`users_id` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'トピック';


-- -----------------------------------------------------
-- Table `eg_bbs`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eg_bbs`.`comments` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `users_id` BIGINT NOT NULL COMMENT 'ユーザーID',
  `topics_id` BIGINT NOT NULL COMMENT 'トピックID',
  `body` TEXT NOT NULL COMMENT 'コメント本文（※アプリで2000文字の制御を入れる。）',
  `created` DATETIME NOT NULL COMMENT '作成日時',
  `updated` DATETIME NOT NULL COMMENT '更新日時',
  PRIMARY KEY (`id`),
  INDEX `fk_comments_topics_idx` (`topics_id` ASC) VISIBLE,
  INDEX `fk_comments_users1_idx` (`users_id` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'コメント';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
