version: '3.6'

services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=eg_bbs
      - MYSQL_ROOT_PASSWORD=rootroot
      - MYSQL_USER=eg_user
      - MYSQL_PASSWORD=eg_pass
      - TZ=Asia/Tokyo
    volumes:
      - ./data/db:/var/lib/mysql
      - type: bind
        source:  ./containers/mysql/my.cnf
        target: /etc/mysql/conf.d/my.cnf
    ports:
      - 13306:3306
