-- MySQL Script generated by MySQL Workbench
-- Thu Feb  2 19:43:28 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema eg_bbs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eg_bbs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eg_bbs` DEFAULT CHARACTER SET utf8 ;
USE `eg_bbs` ;

-- -----------------------------------------------------
-- Table `eg_bbs`.`topics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eg_bbs`.`topics` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `title` VARCHAR(128) NOT NULL COMMENT 'タイトル',
  `body` TEXT NOT NULL COMMENT '本文',
  `pin_code` INT NOT NULL COMMENT '暗証コード（※コードが一致したら編集可能）',
  `nickname` VARCHAR(32) NULL COMMENT 'ニックネーム',
  `created` DATETIME NOT NULL COMMENT '作成日時',
  `updated` DATETIME NOT NULL COMMENT '更新日時',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'トピック';


-- -----------------------------------------------------
-- Table `eg_bbs`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eg_bbs`.`comments` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `topics_id` BIGINT NOT NULL COMMENT 'トピックID',
  `body` TEXT NOT NULL COMMENT 'コメント本文',
  `pin_code` INT NOT NULL COMMENT '暗証コード（※コードが一致したら編集可能）',
  `nickname` VARCHAR(32) NULL COMMENT 'ニックネーム',
  `created` DATETIME NOT NULL COMMENT '作成日時',
  `updated` DATETIME NOT NULL COMMENT '更新日時',
  PRIMARY KEY (`id`),
  INDEX `fk_comments_topics_idx` (`topics_id` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'コメント';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
